### ISSUE TITLE
mouseout is not a good way.

### ISSUE THREAD

**Issue by daybrush** [dropy-online/boardy#21]
https://github.com/load0ne/boardy/blob/master/src/modules/Trigger/Trigger.ts#L94

mouseout is not a good way.
The drag range is too narrow.
I want to have continuity unless mouse up.

**Comment by load0ne** [comment]
I think your UX opinion is so cool. 👍 
since the Trigger is just an Event Emitter, we will modify the logic of the default pen tool. 

https://github.com/load0ne/boardy/blob/master/src/modules/Painter/tools/blackline.ts#L28

**Comment by load0ne** [comment]
It was applied in this PR. thank you 😄 
https://github.com/dropy-online/boardy/pull/25
