### ISSUE TITLE
The drag range is narrow.

### ISSUE THREAD

**Issue by daybrush** [dropy-online/boardy#22]
The drag range is narrow.
https://github.com/load0ne/boardy/blob/master/src/modules/Trigger/Trigger.ts#L42-L43
If the drag range is narrow, it is inconvenient to use.
I think the `window` is good for the drag range.

**Comment by load0ne** [comment]
@daybrush  Thank you for a good point.
this is an area that must be improved. 

we need to attach an event to the `window`
and provide a way for the user to handle the `in-canvas` and `non-canvas` events.

**Comment by load0ne** [comment]
It was applied in this PR. thank you 😄 
https://github.com/dropy-online/boardy/pull/25
