### ISSUE TITLE
Is it okay to send an event every time without dragging?

### ISSUE THREAD

**Issue by daybrush** [dropy-online/boardy#23]
Is it okay to send an event every time without dragging?

This is only necessary 0, 1, and 2 events?

mousedown 0
drag 1
mosueup 2
mouseout 3
mousemove 4

**Comment by load0ne** [comment]
@daybrush 
To explain this part, we must first tell the history of the development of this module. :-)

in our app, we needed three tools with real-time sketching capabilities.
the three tools are pen, crayon, **laser pointer**.

the reason **it is difficult to implement simply by converting the cursor image** is
that the laser pointer also needs to be real-time communication. so this **needs to be painted**.

as a result, we need a `mousemove` event.
But your `draw event` idea seems really good. I will reflect it. 👍

**Comment by load0ne** [comment]
It was applied in this PR. thank you 😄 
https://github.com/dropy-online/boardy/pull/25
