### ISSUE TITLE
requestAnimationFrame is running without meaning.

### ISSUE THREAD

**Issue by daybrush** [dropy-online/boardy#24]
requestAnimationFrame is running without meaning.

You may be trying to handle multiple actions at frame timing.
https://github.com/dropy-online/boardy/blob/master/src/modules/Renderer/Renderer.ts#L22

What about the code below?
```ts
public render(action: Action): void {
    this.actionQueue.push(action);
    if (!this.flag) {
       this.flag = true;
        window.requestAnimationFrame(this.animate);
    }
}
private readonly animate = () => {
    this.flag = false;
    this.actionQueue.forEach((action) => {
      if (!action) return;
      this.painter.paint(action);
    });
    this.actionQueue = [];
    this.rasterizer.rasterize();
  }
```

**Comment by load0ne** [comment]
@daybrush  oh it's good idea!
In addition, i need to change the variable name `flag` to `isRunning`.

**Comment by load0ne** [comment]
It was applied in this PR. thank you 😄 
https://github.com/dropy-online/boardy/pull/25
